version: "3.7"

services:
    logger-golang-service:
        build:
            context: .
            dockerfile: ./compose/local/golang/Dockerfile
        image: logger_golang_dev
        container_name: logger_golang_dev
        volumes:
            - .:/app:z
        env_file:
            - ./.envs/.local/.golang
        command: /start
        ports:
            - 8080:8080
