version: "3.7"

services:
    logger-golang:
        build:
            context: .
            dockerfile: ./compose/production/golang/Dockerfile
        container_name: logger_golang
        env_file:
            - ./.envs/.production/.golang
        command: /start
        ports:
            - 8080:8080

