version: "3.7"

services:
    golang:
        build:
            context: .
            dockerfile: ./compose/production/golang/Dockerfile
        image: golang
        env_file:
            - ./.envs/.production/.golang
        ports:
            - 8080:8080