app:
  name: 'logger-project'
  version: '1.0.0'
  api_key: 'dummy'

http:
  port: '8080'

logger:
  log_level: 'info'

admin:
  username: 'admin@gmail.com'
  password: '0123456789'

the_hill_admin:
  name: 'the_hill_admin'
  amount: 100

the_hill_customer:
  name: 'the_hill_customer'
  amount: 500

the_hill_store:
  name: 'the_hill_store'
  amount: 500
